version: 0.2

phases:
  build:
    commands:
      - echo Building docker image on `date`
      - cd $(echo ${CODEBUILD_INITIATOR} | cut -d'/' -f2)
      - pwd

artifacts:
  files:
    - $CODEBUILD_INITIATOR/*
    - $(echo ${CODEBUILD_INITIATOR} | cut -d'/' -f2)/*

